<?php

namespace DashboardBundle\Repository;

use DashboardBundle\Entity\Salon;
use Doctrine\ORM\EntityRepository;

/**
 * ChangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeRepository extends EntityRepository
{
    /**
     * @param $status
     * @return array
     */
    public function findByStatus($status)
    {
        return $this->findBy(['status' => $status]);
    }

    /**
     * @param $status
     * @param Salon $salon
     *
     * @return array
     */
    public function findByStatusAndSalon($status, Salon $salon)
    {
        return $this->findBy(['status' => $status, 'salon' => $salon]);
    }

    /**
     * @param Salon $salon
     * @return array
     */
    public function findBySalon(Salon $salon)
    {
        return $this->findBy(['salon' => $salon]);
    }

    /**
     * @param Salon $salon
     * @return array
     */
    public function findByNewSalon(Salon $salon)
    {
        return $this->findBy(['salon' => $salon, 'status' => 'new']);
    }


}
