<?php

namespace DashboardBundle\Repository;

/**
 * CustomerPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
