<?php

namespace DashboardBundle\Repository;

use DashboardBundle\Entity\Salon;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Salon $salon
     * @return array
     */
    public function findBySalon(Salon $salon)
    {
        return $this->findBy(['salon' => $salon]);
    }
}
