<?php

namespace DashboardBundle\Repository;

/**
 * MetroStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetroStationRepository extends \Doctrine\ORM\EntityRepository
{
}
