<?php

namespace Vs\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends EntityRepository
{
}
