<?php

namespace DashboardBundle\Repository;

/**
 * SpecialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialRepository extends \Doctrine\ORM\EntityRepository
{
}
